# Generated by Django 4.2.2 on 2023-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_buyer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='paymentMode',
            field=models.IntegerField(choices=[(0, 'NetBanking'), (1, 'COD')], default=0),
        ),
    ]
