# Generated by Django 4.2.2 on 2023-10-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_checkout_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='paymentMode',
            field=models.IntegerField(choices=[(0, 'COD'), (1, 'NetBanking')], default=0),
        ),
    ]
